#!/bin/sh
#
# support for EFI + GPT
#

if [ "$#" -ne 1 ]; then
    echo "#### You should specify a device, like: $0 /dev/sda"
    exit 1
fi

DEVICE=$1
if [ ! -b ${DEVICE} ]; then
    echo "You should use an available device"
    exit 1
fi

# reference:
#    1. https://wiki.archlinux.org/index.php/Parted
#    2. https://www.gnu.org/software/parted/manual/html_node/set.html
if [[ -z "$(blkid -L RANCHER_STATE)" ]]; then
    parted -s ${DEVICE} mklabel gpt
    parted -s ${DEVICE} mkpart primary ext4 0% 500MB
    parted -s ${DEVICE} mkpart primary ext4 500MB 100%
    parted -s ${DEVICE} set 1 esp on
    mkfs.vfat -F 32 ${DEVICE}1
    mkfs.ext4 -F -L RANCHER_STATE ${DEVICE}2
else
    echo "#### You have installed to disk"
    exit 1
fi

ISO_DEVICE=$(blkid -L K3OS)
if [ -z "${ISO_DEVICE}" ]; then
    echo "#### There is no k3os ISO device"
    exit 1
fi

BOOT_TMP=/tmp/boot_tmp
mkdir -p ${BOOT_TMP}
mount -t iso9660 -o loop ${ISO_DEVICE} ${BOOT_TMP}

# mount boot device and copy boot files
mount -t vfat ${DEVICE}1 /boot
mkdir -p /boot/EFI/syslinux
pushd /boot/EFI/
# copy initrd and syslinux
cp ${BOOT_TMP}/boot/initrd-* .
cp ${BOOT_TMP}/boot/vmlinuz-* .
cp ${BOOT_TMP}/boot/*.cfg .

cp ${BOOT_TMP}/efi64/* ./syslinux
cp ${BOOT_TMP}/boot/isolinux/isolinux.cfg ./syslinux/syslinux.cfg

# modprobe efivars
efibootmgr -c -d /dev/sda -p 1 -l \\EFI\\syslinux\\syslinux.efi -L "SYSLINUX"
#efibootmgr -o 0000,0001,0002
popd

umount /boot
umount ${BOOT_TMP}
rm -rf ${BOOT_TMP}
