#!/bin/sh
#
# called by k3os os upgrade
#
# set -ex

INITRD_URL=$1
VMLINUZ_URL=$2
VERSION=$3
KERNEL_VERSION=$4

wget -O /boot/initrd-${VERSION} ${INITRD_URL}
wget -O /boot/vmlinuz-${KERNEL_VERSION} ${VMLINUZ_URL}

mv /boot/linux-current.cfg /boot/linux-previous.cfg

cat << EOF > /boot/linux-current.cfg
DEFAULT k3os-${VERSION}
LABEL k3os-${VERSION}
    SAY k3os-${VERSION}: K3OS ${VERSION} ${KERNEL_VERSION}
    MENU LABEL K3OS ${VERSION} ${KERNEL_VERSION}
    KERNEL ../vmlinuz-${KERNEL_VERSION}
    INITRD ../initrd-${VERSION}
    # see global.cfg for kernel boot parameters

MENU SEPARATOR
EOF

