#!/bin/sh

if [ $EUID -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
fi

if [ "$#" -ne 1 ]; then
    echo "You should specify a local patch for config file, like: $0 /tmp/cloud-config.yml"
    exit 1
fi
CONFIG_FILE=$1

STATE_DEVICE=$(blkid -L RANCHER_STATE)
if [ -z "${STATE_DEVICE}" ]; then
    echo "There is no available device, LABEL=RANCHER_STATE"
    exit 1
fi

TMP_STATE="/tmp/state"
mkdir -p ${TMP_STATE}
mount ${STATE_DEVICE} ${TMP_STATE}

CONF_DIR=${TMP_STATE}/system-data/var/lib/k3os/conf/cloud-config.d
mkdir -p ${CONF_DIR}
cp $CONFIG_FILE ${CONF_DIR}

umount ${TMP_STATE}
