#!/bin/sh
#
# called by k3os os upgrade
#
# set -ex

INITRD_URL=$1
VMLINUZ_URL=$2
VERSION=$3
KERNEL_VERSION=$4

PREVIOUS_CFG=/boot/linux-previous.cfg
CURRENT_CFG=/boot/linux-current.cfg

# a previous version exists here, we need to remove the oldest one.
if [ -f ${PREVIOUS_CFG} ]; then
    PRE_INITRD=$(cat ${PREVIOUS_CFG} | grep initrd | awk -F '/' '{print $2}')
    PRE_VMLINUZ=$(cat ${PREVIOUS_CFG} | grep vmlinuz | awk -F '/' '{print $2}')
    rm -vf /boot/${PRE_INITRD}
    rm -vf /boot/${PRE_VMLINUZ}
fi

wget -O /boot/initrd-${VERSION} ${INITRD_URL}
wget -O /boot/vmlinuz-${KERNEL_VERSION} ${VMLINUZ_URL}

mv ${CURRENT_CFG} ${PREVIOUS_CFG}

cat << EOF > ${CURRENT_CFG}
DEFAULT k3os-${VERSION}
LABEL k3os-${VERSION}
    SAY k3os-${VERSION}: K3OS ${VERSION} ${KERNEL_VERSION}
    MENU LABEL K3OS ${VERSION} ${KERNEL_VERSION}
    KERNEL ../vmlinuz-${KERNEL_VERSION}
    INITRD ../initrd-${VERSION}
    # see global.cfg for kernel boot parameters

MENU SEPARATOR
EOF

