#!/bin/sh

mount -t devtmpfs devtmpfs /dev

BASE_DIR=/var/lib/k3os/squashfs
mount -t squashfs -o loop ${BASE_DIR}/modules.squashfs /usr/lib/modules
mount -t squashfs -o loop ${BASE_DIR}/firmware.squashfs /usr/lib/firmware

mount -a
