#!/bin/sh

if [ $EUID -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
fi

BIOS_BOOT_DEVICE=$(blkid -L RANCHER_BIOS)
if [ ! -z "${BIOS_BOOT_DEVICE}" ]; then
    mount ${BIOS_BOOT_DEVICE} /boot
fi

EFI_BOOT_DEVICE=$(blkid -L RANCHER_EFI)
if [ ! -z "${EFI_BOOT_DEVICE}" ]; then
    mount ${EFI_BOOT_DEVICE} /boot
fi

TMP_DIR=/tmp/writablefs
mkdir -p ${TMP_DIR}
trap "rm -rf ${TMP_DIR}" EXIT


# The magic dirs and files
MAGICS="/etc/ssh
        /etc/rc.local
        /var/db/dhcpcd
        /etc/default
        /etc/logrotate.d
        /etc/rsyslog.d
        /etc/hosts
        /home/rancher
        /var/lib/k3os/conf
        /etc/rancher
        /var/lib/rancher
        /mnt
        /media"

STATE_DEVICE=$(blkid -L RANCHER_STATE)
if [ -z "${STATE_DEVICE}" ]; then
    echo "No LABEL=RANCHER_STATE device, so we use tmpfs"

    for i in ${MAGICS}; do
        case $i in
            "/etc/ssh")
                mkdir -p ${TMP_DIR}/etc/ssh
                cp -arf ${i}/* ${TMP_DIR}/etc/ssh
                mount -t tmpfs tmpfs /etc/ssh
                cp -arf ${TMP_DIR}/etc/ssh/* /etc/ssh
                ;;
            "/etc/hosts")
                cat /etc/hosts > /tmp/hosts
                mount -o bind /tmp/hosts /etc/hosts
                ;;
            *)
                mount -t tmpfs -o mode=755 tmpfs ${i}
                ;;
        esac
    done

    chown -R rancher:rancher /home/rancher

    exit 0
fi

# mount the writable filesystem

mount ${STATE_DEVICE} /writable

SYSTEMDATA_DIR=/writable/system-data
USERDATA_DIR=/writable/user-data
mkdir -p ${SYSTEMDATA_DIR} ${USERDATA_DIR}

for i in ${MAGICS}; do
    case $i in
        "/etc/ssh")
            if [ ! -d ${SYSTEMDATA_DIR}/etc/ssh ]; then
                mkdir -p ${SYSTEMDATA_DIR}/etc/ssh
                cp -arf /etc/ssh/* ${SYSTEMDATA_DIR}/etc/ssh
            fi
            mount -o bind ${SYSTEMDATA_DIR}/etc/ssh /etc/ssh
            ;;
        "/etc/hosts")
            if [ ! -f ${SYSTEMDATA_DIR}/etc/hosts ]; then
                cat /etc/hosts > ${SYSTEMDATA_DIR}/etc/hosts
            fi
            mount -o bind ${SYSTEMDATA_DIR}/etc/hosts /etc/hosts
            ;;
        "/etc/rc.local")
            if [ ! -f ${SYSTEMDATA_DIR}/etc/rc.local ]; then
                mkdir -p ${SYSTEMDATA_DIR}/etc
                cat /etc/rc.local > ${SYSTEMDATA_DIR}/etc/rc.local
                chmod +x ${SYSTEMDATA_DIR}/etc/rc.local
            fi
            mount -o bind ${SYSTEMDATA_DIR}/etc/rc.local /etc/rc.local
            ;;
        *)
            mkdir -p ${SYSTEMDATA_DIR}/${i}
            mount -o bind ${SYSTEMDATA_DIR}/${i} ${i}
            ;;
    esac
done

chown -R rancher:rancher /home/rancher
