#!/bin/sh

BIOS_BOOT_DEVICE=$(blkid -L RANCHER_BIOS)
if [ ! -z "${BIOS_BOOT_DEVICE}" ]; then
    mount ${BIOS_BOOT_DEVICE} /boot
fi

EFI_BOOT_DEVICE=$(blkid -L RANCHER_EFI)
if [ ! -z "${EFI_BOOT_DEVICE}" ]; then
    mount ${EFI_BOOT_DEVICE} /boot
fi

STATE_DEVICE=$(blkid -L RANCHER_STATE)
if [ -z "${STATE_DEVICE}" ]; then
    echo "No LABEL=RANCHER_STATE device, so we use tmpfs"

    ## for ssh
    mkdir -p /tmp/system-data/etc/ssh
    cp -arf /etc/ssh/* /tmp/system-data/etc/ssh
    mount -t tmpfs tmpfs /etc/ssh
    cp -arf /tmp/system-data/etc/ssh/* /etc/ssh

    ## for dhcpcd
    mount -t tmpfs tmpfs /var/db/dhcpcd

    ## for init default
    mount -t tmpfs tmpfs /etc/default

    ## for logrotate.d
    mount -t tmpfs tmpfs /etc/logrotate.d

    ## for rsyslog
    mount -t tmpfs tmpfs /etc/rsyslog.d

    ## for hosts
    cat /etc/hosts > /tmp/hosts
    mount -o bind /tmp/hosts /etc/hosts

    ## for home
    mount -t tmpfs tmpfs /home/rancher
    chown rancher:rancher /home/rancher

    ## for k3os dir
    mount -t tmpfs tmpfs /var/lib/k3os/conf

    ## for rancher dir
    mount -t tmpfs tmpfs /etc/rancher
    mount -t tmpfs tmpfs /var/lib/rancher

    # clean tmp dir
    rm -rf /tmp/system-data
    exit 0
fi

# hard code for test
mount ${STATE_DEVICE} /writable
mkdir -p /writable/system-data /writable/user-data /writable/tmp

## for ssh
mkdir -p /writable/system-data/etc/ssh
cp -arf /etc/ssh /writable/tmp
mount -o bind /writable/system-data/etc/ssh /etc/ssh
cp -arf /writable/tmp/ssh/* /etc/ssh

## for dhcpcd
mkdir -p /writable/system-data/var/db/dhcpcd
mount -o bind /writable/system-data/var/db/dhcpcd /var/db/dhcpcd

## for init default
mkdir -p /writable/system-data/etc/default
mount -o bind /writable/system-data/etc/default /etc/default

## for logrotate.d
mkdir -p /writable/system-data/etc/logrotate.d
mount -o bind /writable/system-data/etc/logrotate.d /etc/logrotate.d

## for rsyslog
mkdir -p /writable/system-data/etc/rsyslog.d
mount -o bind /writable/system-data/etc/rsyslog.d /etc/rsyslog.d

## for hosts
cat /etc/hosts > /writable/system-data/etc/hosts
mount -o bind /writable/system-data/etc/hosts /etc/hosts

## for home
mkdir -p /writable/user-data/home/rancher
mount -o bind /writable/user-data/home/rancher /home/rancher
chown rancher:rancher /home/rancher

## for k3os dir
mkdir -p /writable/system-data/var/lib/k3os/conf
mount -o bind /writable/system-data/var/lib/k3os/conf /var/lib/k3os/conf

## for rancher dir
mkdir -p /writable/system-data/etc/rancher /writable/system-data/var/lib/rancher
mount -o bind /writable/system-data/etc/rancher /etc/rancher
mount -o bind /writable/system-data/var/lib/rancher /var/lib/rancher

# clean tmp dir
rm -rf /writable/tmp
