#!/bin/busybox sh

# Mount the /proc and /sys filesystems.
mkdir -p /proc && mount -t proc proc /proc
mkdir -p /sys && mount -t sysfs sysfs /sys

mkdir -p /state
mount -t squashfs -o loop /rootfs.squashfs /state

mount -t squashfs -o loop /modules.squashfs /state/usr/lib/modules
mount -t squashfs -o loop /firmware.squashfs /state/usr/lib/firmware

# Clean up.
umount /proc
umount /sys

# Boot the real thing.
exec switch_root /state /sbin/init
