#!/bin/bash
set -e

if [ "$K3OS_DEBUG" = true ]; then
    set -x
fi

DEVICE=$K3OS_INSTALL_DEVICE
PARTTABLE=gpt

if [ "$K3OS_INSTALL_EFI" ]; then
    PARTTABLE=efi
elif [ "$K3OS_INSTALL_MSDOS" ]; then
    PARTTABLE=msdos
fi

if [ ! -b ${DEVICE} ]; then
    echo "You should use an available device"
    exit 1
fi

if [ "${PARTTABLE}" != gpt ] && [ "${PARTTABLE}" != msdos ] && [ "${PARTTABLE}" != "efi" ]; then
    echo "Invalid partition table type ${PARTTABLE}, must be either gpt, msdos, efi"
    exit 1
fi

ISO_DEVICE=$(blkid -L K3OS || true)
if [ -z "${ISO_DEVICE}" ]; then
    echo "#### There is no k3os ISO device"
    exit 1
fi

BOOTFLAG=legacy_boot
MBR_FILE=gptmbr.bin
if [ "${PARTTABLE}" = "msdos" ]; then
    BOOTFLAG=boot
    MBR_FILE=mbr.bin
elif [ "${PARTTABLE}" = "efi" ]; then
    EFI=true
    PARTTABLE=gpt
    BOOTFLAG=esp
    if [ ! -e /sys/firmware/efi ]; then
        echo WARNING: installing EFI on to a system that does not support EFI
        HAS_EFI=false
    fi
fi

BOOT=1
STATE=2

dd if=/dev/zero of=${DEVICE} bs=1M count=1
parted -s ${DEVICE} mklabel ${PARTTABLE}
parted -s ${DEVICE} mkpart primary fat32 0% 500MB
parted -s ${DEVICE} mkpart primary ext4 500MB 1000MB
parted -s ${DEVICE} set 1 ${BOOTFLAG} on

PREFIX=${DEVICE}
if [ ! -e ${PREFIX}${STATE} ]; then
    PREFIX=${DEVICE}p
fi

if [ ! -e ${PREFIX}${STATE} ]; then
    echo Failed to find ${PREFIX}${STATE} or ${DEVICE}${STATE} to format
    exit 1
fi

mkfs.ext4 -F -L K3OS_STATE ${PREFIX}${STATE}
mkfs.vfat -F 32 ${PREFIX}${BOOT}
fatlabel ${PREFIX}${BOOT} K3OS_BOOT

TARGET=/run/k3os/target
mkdir -p ${TARGET}
mount ${PREFIX}${STATE} ${TARGET}
mkdir -p ${TARGET}/boot
mount ${PREFIX}${BOOT} ${TARGET}/boot

DISTRO=/run/k3os/iso
mkdir -p $DISTRO
mount $ISO_DEVICE $DISTRO

rsync -av --exclude boot/isolinux ${DISTRO}/ $TARGET
echo $DEVICE $STATE > $TARGET/k3os/system/growpart

mkdir -p ${TARGET}/boot/EFI
cp -rf ${DISTRO}/boot/isolinux ${TARGET}/boot/syslinux
cp -rf ${DISTRO}/boot/isolinux/efi64 ${TARGET}/boot/EFI/syslinux
cp -rf ${DISTRO}/boot/isolinux/efilinux.cfg ${TARGET}/boot/EFI/syslinux/syslinux.cfg

if [ "$EFI" = "true" ]; then
    modprobe efivars 2>/dev/null || true
    if [ "${HAS_EFI}" != "false" ]; then
        efibootmgr -c -d ${DEVICE} -p 1 -l \\EFI\\syslinux\\syslinux.efi -L "SYSLINUX"
    fi
else
    syslinux --directory /syslinux --install ${PREFIX}${BOOT}
    dd bs=440 conv=notrunc count=1 if=/usr/share/syslinux/${MBR_FILE} of=${DEVICE}
fi

if [ -n "$K3OS_INSTALL_CONFIG_URL" ]; then
    cp "$K3OS_INSTALL_CONFIG_URL" ${TARGET}/k3os/system/config.yaml
    chmod 600 ${TARGET}/k3os/system/config.yaml
fi

umount ${TARGET}/boot
rmdir ${TARGET}/boot
umount ${TARGET}
