#!/bin/sh

if [ $EUID -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
fi

EFI_BOOT_DEVICE=$(blkid -L RANCHER_EFI)
if [ ! -z "${EFI_BOOT_DEVICE}" ]; then
    mount ${EFI_BOOT_DEVICE} /boot
fi

TMP_DIR=/tmp/writablefs
mkdir -p ${TMP_DIR}
trap "rm -rf ${TMP_DIR}" EXIT


# The magic dirs and files
MAGICS="/var/db/dhcpcd
        /var/lib/rancher
        /var/lib/cni
        /home/rancher
        /mnt
        /media"

STATE_DEVICE=$(blkid -L RANCHER_STATE)
if [ -z "${STATE_DEVICE}" ]; then
    echo "No LABEL=RANCHER_STATE device, so we use tmpfs"

    for i in ${MAGICS}; do
        mount -t tmpfs -o mode=755 tmpfs ${i}
    done

    chown -R rancher:rancher /home/rancher

    exit 0
fi

# mount the writable filesystem

SYSTEMDATA_DIR=/writable/system-data
USERDATA_DIR=/writable/user-data
mkdir -p ${SYSTEMDATA_DIR} ${USERDATA_DIR}

for i in ${MAGICS}; do
    mkdir -p ${SYSTEMDATA_DIR}/${i}
    mount -o bind ${SYSTEMDATA_DIR}/${i} ${i}
done

if [ ! -z "$(blkid -L SYSTEM_BOOT)" ]; then
    # RPi needs this partition
    mount LABEL=SYSTEM_BOOT /boot
else
    # bind mount boot dir
    if [ -d /writable/boot ]; then
        mount -o bind /writable/boot /boot
    fi
fi

chown -R rancher:rancher /home/rancher
