#!/bin/bash
set -e

if [ $(whoami) != "root" ]
then
	echo "This script must be run as root."
	exit 1
fi

PROC=$(uname -m)
if [ $PROC == "x86_64" ]
then
	ARCH="amd64"
elif [ $PROC == "aarch64" ]
then
	ARCH="arm64"
elif [ $PROC == "armv7l" ]
then
	ARCH="arm"
else
	echo "Unsupported CPU architecture."
	exit 1
fi

: ${K3OS_UPGRADE_CHANNEL:=${K3OS_UPDATE_CHANNEL_URL:="github-releases://rancher/k3os"}}
: ${K3OS_UPGRADE_VERSION:=${K3OS_VERSION:="latest"}}

echo "Upgrading rootfs for k3OS ${K3OS_UPGRADE_VERSION}"
/usr/libexec/k3os/k3os-operator upgrade --rootfs --remount --sync \
	--channel=${K3OS_UPGRADE_CHANNEL} --version=${K3OS_UPGRADE_VERSION} 
echo "Upgrade complete! Please reboot."
