#!/bin/bash

. /etc/os-release
cat > /etc/issue << "COW"
               ,        ,
  ,------------|'------'|  _     ____
 / .           '-'    |-' | |   |___ \\
 \\/|             |    |   | | __  __) |  ___   ___
   |   .________.'----'   | |/ / |__ <  / _ \\ / __|
   |   |        |   |     |   <  ___) || (_) |\\__ \\
   \\___/        \\___/     |_|\\_\\|____/  \\___/ |___/

COW

cat >> /etc/issue << EOF
$PRETTY_NAME
Kernel \r on an \m (\l)

================================================================================
NIC              State          Address
$(ip -br addr show | grep -E -v '^(lo|flannel|cni|veth)')
================================================================================
EOF
cat >> /etc/issue << "EOF"

Welcome to k3OS (login with user: rancher)
EOF
