#!/bin/sh

case "$1" in
  start)
        echo "Start writablefs"
        /usr/lib/k3os/writablefs
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
