#!/bin/sh

case "$1" in
  start)
        echo "Start k3os entrypoint"
        k3os entrypoint
        echo "Start k3os sysinit"
        /usr/lib/k3os/k3os-sysinit
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
