#!/bin/sh

case "$1" in
  start)
        echo "Start k3os network"
        k3os-netinit
        source /etc/profile
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
