#!/bin/sh
#

NAME="k3s-service"

start()
{
    printf "Starting ${NAME}: "
    /usr/lib/k3os/${NAME} start
}

stop()
{
    printf "Stopping ${NAME}: "
    /usr/lib/k3os/${NAME} stop
}

case "$1" in
  start)
      start
      ;;
  stop)
      stop
      ;;
  restart|reload)
      # TODO: how to
      ;;
  *)
      echo "Usage: $0 {start|stop|restart}"
      exit 1
esac

exit $?
