#!/bin/bash
A="$(echo "$@" | sed 's!-hfsplus -apm-block-size 2048 -hfsplus-file-creator-type chrp tbxj /System/Library/CoreServices/.disk_label -hfs-bless-by i /System/Library/CoreServices/boot.efi!!')"
echo $A >> /tmp/args
exec xorriso $A
