#!/bin/sh
#
# Copyright IBM, Corp. 2010  
#
# Authors:
#  Anthony Liguori <aliguori@us.ibm.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.

# Set to the name of your bridge
BRIDGE=k3os_vmbr0

do_brctl() {
    brctl "$@"
}

do_ifconfig() {
    ifconfig "$@"
}


check_bridge() {
    if do_brctl show | grep "^$1" > /dev/null 2> /dev/null; then
	return 1
    else
	return 0
    fi
}


delete_bridge() {
    do_ifconfig "$1" down
    do_brctl delbr "$1"
}

delete_bridge_nat() {
    if ! check_bridge "$1" ; then
	delete_bridge "$1"
    fi
}

delete_bridge_nat "$BRIDGE"


