#!/bin/bash
set -e

# Override using a local kernel build
if [ -e ${DAPPER_SOURCE}/assets/kernel.tar.gz ]; then
    echo "copying ${DAPPER_SOURCE}/assets/kernel.tar.gz ${DOWNLOADS}/kernel.tar.gz"
    cp ${DAPPER_SOURCE}/assets/kernel.tar.gz ${DOWNLOADS}/kernel.tar.gz
fi

mkdir -p ${BUILD}/kernel
tar xf ${DOWNLOADS}/kernel.tar.gz -C ${BUILD}/kernel

for i in vmlinuz vmlinux; do
    if [ -e ${BUILD}/kernel/boot/${i}-* ]; then
        mkdir -p ${ARTIFACTS}
        echo "Copy ${BUILD}/kernel/boot/${i}-* to ${ARTIFACTS}/vmlinuz-${KERNEL_VERSION}"
        cp ${BUILD}/kernel/boot/${i}-* ${ARTIFACTS}/vmlinuz-${KERNEL_VERSION}
        cp ${BUILD}/kernel/boot/${i}-* ${BUILD}/kernel/vmlinuz
        break
    fi
done

if [ -d ${BUILD}/kernel/lib ]; then
    rm -rf ${INITRD_DIR}/usr/lib
    cp -rf ${BUILD}/kernel/lib ${INITRD_DIR}/usr/
    depmod -b ${INITRD_DIR}/usr $(basename ${INITRD_DIR}/usr/lib/modules/*)
fi
