#!/bin/bash
set -e

mkdir -p ${ROOTFS_DIR}

# Override using a local rootfs build
if [ -e ${DAPPER_SOURCE}/assets/rootfs.tar ]; then
    echo "copying ${DAPPER_SOURCE}/assets/rootfs.tar ${DOWNLOADS}/rootfs.tar"
    cp ${DAPPER_SOURCE}/assets/rootfs.tar ${DOWNLOADS}/rootfs.tar
fi

tar xf ${DOWNLOADS}/rootfs.tar -C ${ROOTFS_DIR}

cp -rf assets/rootfs/* ${ROOTFS_DIR}/

# construct rootfs
mkdir -p ${ROOTFS_DIR}/usr/lib/modules ${ROOTFS_DIR}/usr/lib/firmware
mkdir -p ${ROOTFS_DIR}/writable
mkdir -p ${ROOTFS_DIR}/var/lib/k3os/squashfs
