#!/bin/bash
set -e

if [ "${ARCH}" == "amd64" ]; then
    # for bios
    mkdir -p ${BOOTLOADER_DIR}/bios
    cp /usr/lib/syslinux/modules/bios/* ${BOOTLOADER_DIR}/bios

    # for efi64
    mkdir -p ${BOOTLOADER_DIR}/efi64
    cp /usr/lib/syslinux/modules/efi64/* ${BOOTLOADER_DIR}/efi64

    # extlinux binary
    apt-get install -y --no-install-recommends extlinux
    mkdir -p ${BOOTLOADER_DIR}/bin
    cp /usr/bin/extlinux ${BOOTLOADER_DIR}/bin

    # syslinux mbr
    mkdir -p ${BOOTLOADER_DIR}/mbr
    cp /usr/lib/syslinux/mbr/* ${BOOTLOADER_DIR}/mbr
fi
