#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

ARTIFACTS=$(pwd)/dist/artifacts
BUILD=build
INITRD_DIR=${BUILD}/initrd
ROOTFS_DIR=${BUILD}/rootfs
KERNEL_DIR=${BUILD}/kernel
BOOTLOADER_DIR=${BUILD}/bootloader
export ARTIFACTS BUILD INITRD_DIR ROOTFS_DIR KERNEL_DIR BOOTLOADER_DIR VERSION

mkdir -p ${ARTIFACTS} ${DOWNLOADS}

./scripts/layout-bootloader
./scripts/layout-kernel
./scripts/layout-rootfs
./scripts/layout-initrd

pushd $(dirname $0)/../build/initrd
md5sum $(find -type f | sort -u ) | md5sum - | awk '{print $1}' > .id
popd
