#!/bin/bash
set -e

mkdir -p ${INITRD_DIR}

# Override using a local initrdfs build
if [ -e ${DAPPER_SOURCE}/assets/initrdfs.tar ]; then
    echo "copying ${DAPPER_SOURCE}/assets/initrdfs.tar ${DOWNLOADS}/initrdfs.tar"
    cp ${DAPPER_SOURCE}/assets/initrdfs.tar ${DOWNLOADS}/initrdfs.tar
else
    pushd /tmp
    curl -sSL ${!INITRDFS_URL} | tar xvJf -
    mv rootfs.tar ${DOWNLOADS}/initrdfs.tar
    popd
fi

tar xf ${DOWNLOADS}/initrdfs.tar -C ${INITRD_DIR}

cp assets/initrdfs/init ${INITRD_DIR}/
