#!/bin/bash
set -e

# Override using a local kernel build
if [ -e ${DAPPER_SOURCE}/assets/kernel.tar.xz ]; then
    echo "copying ${DAPPER_SOURCE}/assets/kernel.tar.xz ${DOWNLOADS}/kernel.tar.xz"
    cp ${DAPPER_SOURCE}/assets/kernel.tar.xz ${DOWNLOADS}/kernel.tar.xz
else
    if [ -n "${!KERNEL_URL}" ]; then
        curl -fL ${!KERNEL_URL} > ${DOWNLOADS}/kernel.tar.xz
    fi
fi

mkdir -p ${KERNEL_DIR}
tar xf ${DOWNLOADS}/kernel.tar.xz -C ${KERNEL_DIR}

# Use kernel-extra if possible
if [ -e ${DAPPER_SOURCE}/assets/kernel-extra.tar.xz ]; then
    cp ${DAPPER_SOURCE}/assets/kernel-extra.tar.xz ${DOWNLOADS}/kernel-extra.tar.xz
    tar xf ${DOWNLOADS}/kernel-extra.tar.xz -C ${KERNEL_DIR}
fi

if [ -e ${KERNEL_DIR}/boot/vmlinuz-* ]; then
    echo "Copy ${KERNEL_DIR}/boot/vmlinuz-* to ${ARTIFACTS}/vmlinuz${SUFFIX}-${KERNEL_VERSION}"
    cp ${KERNEL_DIR}/boot/vmlinuz-* ${ARTIFACTS}/vmlinuz${SUFFIX}-${KERNEL_VERSION}
    cp ${KERNEL_DIR}/boot/vmlinuz-* ${KERNEL_DIR}/vmlinuz${SUFFIX}
fi

depmod -b ${KERNEL_DIR} $(basename ${KERNEL_DIR}/lib/modules/*)
