#!/bin/bash
set -e

# Override using a local kernel build
if [ -e ${DAPPER_SOURCE}/assets/kernel.tar.gz ]; then
    echo "copying ${DAPPER_SOURCE}/assets/kernel.tar.gz ${DOWNLOADS}/kernel.tar.gz"
    cp ${DAPPER_SOURCE}/assets/kernel.tar.gz ${DOWNLOADS}/kernel.tar.gz
fi

mkdir -p ${BUILD}/kernel
tar xf ${DOWNLOADS}/kernel.tar.gz -C ${BUILD}/kernel

if [ -e ${BUILD}/kernel/boot/vmlinuz-* ]; then
    mkdir -p ${ARTIFACTS}
    echo "Copy ${BUILD}/kernel/boot/vmlinuz-* to ${ARTIFACTS}/vmlinuz-${KERNEL_VERSION}"
    cp ${BUILD}/kernel/boot/vmlinuz-* ${ARTIFACTS}/vmlinuz-${KERNEL_VERSION}
    cp ${BUILD}/kernel/boot/vmlinuz-* ${BUILD}/kernel/vmlinuz
fi

if [ -d ${BUILD}/kernel/lib ]; then
    cp -rf ${BUILD}/kernel/lib ${INITRD_DIR}/usr/
    depmod -b ${INITRD_DIR}/usr $(basename ${INITRD_DIR}/usr/lib/modules/*)
fi
