#!/bin/bash
set -e

cd $(dirname $0)/..

source scripts/version

tar czf ${ARTIFACTS}/rootfs${SUFFIX}.tar.gz --exclude lib/modules --exclude lib/firmware -C ${ROOTFS_DIR} .

mksquashfs ${ROOTFS_DIR} ${ARTIFACTS}/rootfs${SUFFIX}.squashfs
