#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

ISO=${ARTIFACTS}/k3os.iso

bootiso=${BUILD}/bootiso
rm -rf ${bootiso}/

# add bios and efi64 loader files
# it's for installing to disk
mkdir -p ${bootiso}/bios ${bootiso}/mbr
cp -rf ${BOOTLOADER_DIR}/bios/* ${bootiso}/bios
cp -rf ${BOOTLOADER_DIR}/mbr/* ${bootiso}/mbr


# add isolinux for booting from ISO
mkdir -p ${bootiso}/boot ${bootiso}/boot/isolinux/
cat scripts/syslinux/isolinux.cfg | envsubst > ${bootiso}/boot/isolinux/isolinux.cfg
cat scripts/syslinux/isolinux_label.cfg | LABEL=${VERSION} envsubst > ${bootiso}/boot/linux-current.cfg
cat scripts/syslinux/global.cfg | envsubst > ${bootiso}/boot/global.cfg
#cp scripts/syslinux/rancher.png ${bootiso}/boot/


cp ${ARTIFACTS}/${INITRD}                      ${bootiso}/boot/
cp ${ARTIFACTS}/vmlinuz-${KERNEL_VERSION}      ${bootiso}/boot/

cp /usr/lib/ISOLINUX/isolinux.bin              ${bootiso}/boot/isolinux/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32  ${bootiso}/boot/isolinux/
cp /usr/lib/syslinux/modules/bios/*.c32        ${bootiso}/boot/isolinux/

pushd ${bootiso}
xorriso -as mkisofs \
    -l -J -R -V "K3OS" \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    -b boot/isolinux/isolinux.bin -c boot/isolinux/boot.cat \
    -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -o $ISO .
popd
