#!/bin/bash
set -e

# add rootfs.squashfs
cp ${ARTIFACTS}/rootfs${SUFFIX}.squashfs ${INITRD_DIR}/rootfs.squashfs

# add modules.squashfs
cp ${ARTIFACTS}/modules${SUFFIX}.squashfs ${INITRD_DIR}/modules.squashfs

# add firmware.squashfs
cp ${ARTIFACTS}/firmware${SUFFIX}.squashfs ${INITRD_DIR}/firmware.squashfs

pushd ${INITRD_DIR}
echo Creating ${ARTIFACTS}/${INITRD}
find | cpio -H newc -o | gzip -9 > ${ARTIFACTS}/${INITRD}
echo Done creating ${ARTIFACTS}/${INITRD}
popd
