#!/bin/bash
set -e
set -x

source $(dirname $0)/version
cd $(dirname $0)/..

ARTIFACTS=$(pwd)/dist/artifacts
CD=${BUILD}/cd
rm -rf ${CD}/
ISO=${ARTIFACTS}/k3os.iso

mkdir -p ${CD}/boot/isolinux

cp ${ARTIFACTS}/${INITRD} ${CD}/boot
cp ${ARTIFACTS}/vmlinuz-${KERNEL_VERSION} ${CD}/boot/

DIST=$(pwd)/dist
cp -r ${DIST}/boot/* ${CD}/boot/

cp /usr/lib/ISOLINUX/isolinux.bin              ${CD}/boot/isolinux/
cp /usr/lib/syslinux/modules/bios/ldlinux.c32  ${CD}/boot/isolinux/
cp /usr/lib/syslinux/modules/bios/*.c32        ${CD}/boot/isolinux/

cd ${CD} && xorriso \
    -as mkisofs \
    -l -J -R -V "K3OS" \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    -b boot/isolinux/isolinux.bin -c boot/isolinux/boot.cat \
    -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -o $ISO ${CD}

cd $(dirname $ISO)
