#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

bash -x ./scripts/build

ID=$(docker run --net=host --privileged --rm -itd $REPO/k3os-qemu:$TAG run-kvm.sh)
docker attach $ID || docker kill $ID
