#!/bin/bash
set -e
set -x

cd $(dirname $0)/..

source ./scripts/run-common

MEMORY=2048

while [ "$#" -gt 0 ]; do
    case $1 in
        --debug)
            DEBUG=1
            ;;
        --append)
            shift 1
            QEMU_APPEND="${QEMU_APPEND} $1"
            ;;
        --memory)
            shift 1
            MEMORY="$1"
            ;;
        --no-rebuild)
            REBUILD=0
            ;;
        --iso)
            BOOT_ISO=1
            REBUILD=0
            ;;
        *)
            break
            ;;
    esac
    shift 1
done



if [[ ! -e ${KERNEL} || ! -e ${INITRD_SRC} ]]; then
    echo "Failed to find ${KERNEL} or ${INITRD_SRC}" 1>&2
    exit 1
fi

echo "initrd ${INITRD}"
if [ "$REBUILD" == "1" ] || [ ! -e ${INITRD} ]; then
    echo "rebuilding ${INITRD} from ${INITRD_SRC}"
    pushd ${INITRD_SRC} >/dev/null
    find . | cpio -H newc -o | gzip -1 > ${INITRD}
    popd >/dev/null
fi


HD=${BASE}/state/hd.img
if [ ! -e ${HD} ]; then
    mkdir -p $(dirname ${HD})
    qemu-img create -f qcow2 -o size=10G ${HD}
fi

KERNEL_ARGS="${DEFAULT_KERNEL_ARGS} ${QEMU_APPEND}"

if [ "$BOOT_ISO" == "1" ]; then
    ISO_OPTS="-boot c -cdrom ./dist/artifacts/k3os.iso"
        echo "----- $ISO_OPTS"

    exec qemu-system-${QEMUARCH} \
            -nographic \
            -serial mon:stdio \
            -display none \
            -rtc base=utc,clock=host \
            -enable-kvm \
            -cpu host \
            -m 2048 \
            -net nic,vlan=0,model=virtio \
            -net user,vlan=0,hostfwd=tcp::2222-:22,hostname=rancher-dev \
            -drive if=virtio,file=${HD}\
            -smp 1 \
            ${ISO_OPTS} \
            -device virtio-rng-pci
else
    exec qemu-system-x86_64 \
            -nographic \
            -serial mon:stdio \
            -display none \
            -rtc base=utc,clock=host \
            -kernel ${KERNEL} \
            -initrd ${INITRD} \
            -append "${KERNEL_ARGS}" \
            -enable-kvm \
            -cpu host \
            -m 2048 \
            -net nic,vlan=0,model=virtio \
            -net user,vlan=0,hostfwd=tcp::2222-:22,hostname=rancher-dev \
            -drive if=virtio,file=${HD}\
            -smp 1 \
            -device virtio-rng-pci \
            -fsdev local,security_model=none,id=fsdev1,path=/root \
            -device virtio-9p-pci,id=fs1,fsdev=fsdev1,mount_tag=home
fi

