#!/bin/bash
. $(dirname $0)/version
: ${STATEDIR:=$(dirname $0)/../build/state/k3os-$TAG} # unique value per vm instance

set -e

if [ ! -e $STATEDIR/disk.img ]; then
    mkdir -p $STATEDIR
    qemu-img create -f qcow2 $STATEDIR/disk.img 20g
fi

exec ${QEMU_SYSTEM:=qemu-system-$(uname -m)} \
    -m 1280 \
    -machine accel=${QEMU_MACHINE_ACCEL:="hax:kvm:hvf:tcg"} \
    -nographic \
    -serial mon:stdio \
    -rtc base=utc,clock=rt \
    -cdrom $(dirname $0)/../dist/artifacts/k3os-$ARCH.iso \
    -drive if=virtio,file=$STATEDIR/disk.img
